runtime: php72

default_expiration: "10m"

handlers:
- url: /static
  static_dir: static
  secure: always
  redirect_http_response_code: 301

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  secure: always
  redirect_http_response_code: 301

- url: .*
  script: auto
  secure: always
  redirect_http_response_code: 301
